[package]
name = "ui-terminal"
version = "0.1.0"
authors = ["Ilya Bylich <ibylich@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ui-abstract = { path = "../ui-abstract" }
terminal_size = "0.1.13"
